apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/config/bazarr"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv-movies
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/library/movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv-tv
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/library/tv"
