apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: bazarr-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-tv
  namespace: media
spec:
  storageClassName: manual
  volumeName: bazarr-pv-tv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-movies
  namespace: media
spec:
  storageClassName: manual
  volumeName: bazarr-pv-movies
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
