apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: jackett-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-pvc-downloads
  namespace: media
spec:
  storageClassName: manual
  volumeName: jackett-pv-downloads
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400Gi
