apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/config/jackett"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-pv-downloads
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/downloads"
