apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  labels:
    app: plex
    namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: plex
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-pvc-config
        - name: plex-tv
          persistentVolumeClaim:
            claimName: plex-pvc-tv
        - name: plex-movies
          persistentVolumeClaim:
            claimName: plex-pvc-movies
      nodeSelector:
        dedicated: master
      containers:
        - name: plex
          #image: 'ghcr.io/linuxserver/plex:latest'
          #image: 'plexinc/pms-docker:1.25.2.5319-c43dc0277'
          #image: 'linuxserver/plex:1.25.2.5319-c43dc0277-ls93'
          image: 'linuxserver/plex:latest'
          imagePullPolicy: Always
          #resources:
          #  requests:
          #    memory: "254Mi"
          #    cpu: "400m"
          #  limits:
          #    memory: "1024Mi"
          #    cpu: "1000m"
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP  
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP  
            - containerPort: 8324
              name: plex-roku
              protocol: TCP  
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          env:
            - name: TZ
              value: Asia/Jerusalem
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
            - name: VERSION
              value: docker
            - name: ALLOWED_NETWORKS
              value: 192.168.31.0/24, 10.43.0.0/16, 0.0.0.0/0
          volumeMounts:
          - mountPath: /config
            name: plex-config
          - mountPath: /tv
            name: plex-tv
          - mountPath: /movies
            name: plex-movies
      restartPolicy: Always
