apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
  namespace: media
spec:
  selector:
    app: transmission
  ports:
    - name: 'web'
      port: 9091
      protocol: TCP
    - name: 'outside'
      port: 51413
      protocol: TCP
  type: LoadBalancer 
