apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
  labels:
    app: transmission
    namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      volumes:
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-pvc-config
        - name: transmission-watch
          persistentVolumeClaim:
            claimName: transmission-pvc-watch
        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: transmission-pvc-downloads
      nodeSelector:
        dedicated: master
      containers:
        - name: transmission
          image: 'ghcr.io/linuxserver/transmission:version-3.00-r2'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: 'web'
              containerPort: 9091
              protocol: TCP
            - name: 'outside'
              containerPort: 51413
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Jerusalem
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
          volumeMounts:
          - mountPath: /config
            name: transmission-config
          - mountPath: /watch
            name: transmission-watch
          - mountPath: /downloads
            name: transmission-downloads
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 5
            tcpSocket:
              port: 9091
      restartPolicy: Always
