apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-config
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/config/plex"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-movies
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/library/movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-tv
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/library/tv"
