---
groups:
  - name: system-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance)(irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
          alertname: HighCPUUsage
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 2 minutes on {{ $labels.instance }}."

      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.15
        for: 2m
        labels:
          severity: critical
          alertname: LowDiskSpace
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Less than 15% disk space remaining on root (/) of {{ $labels.instance }}."

      - alert: LowSSDSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/mnt/data"} / node_filesystem_size_bytes{mountpoint="/mnt/data"}) < 0.05
        for: 2m
        labels:
          severity: critical
          alertname: LowSSDSpace
        annotations:
          summary: "Low SSD space on {{ $labels.instance }}"
          description: "Less than 5% disk space remaining on /mnt/data of {{ $labels.instance }}."

      - alert: LowMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.2
        for: 2m
        labels:
          severity: warning
          alertname: LowMemory
        annotations:
          summary: "Low memory on {{ $labels.instance }}"
          description: "Less than 20% memory available on {{ $labels.instance }}."

      - alert: HighTemperature
        expr: node_temperature_celsius > 75
        for: 2m
        labels:
          severity: critical
          alertname: HighTemperature
        annotations:
          summary: "High temperature on {{ $labels.instance }}"
          description: "Temperature on {{ $labels.instance }} is above 75°C for more than 2 minutes, indicating possible overheating."

      - alert: HighLoad
        expr: (node_load1 / count(node_cpu_seconds_total{mode="idle"}) * 100) > 80
        for: 2m
        labels:
          severity: critical
          alertname: HighLoad
        annotations:
          summary: "High system load on {{ $labels.instance }}"
          description: "System load on {{ $labels.instance }} is above 80% for more than 2 minutes."

      - alert: HighSwapUsage
        expr: (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes > 0.8
        for: 2m
        labels:
          severity: critical
          alertname: HighSwapUsage
        annotations:
          summary: "High swap usage on {{ $labels.instance }}"
          description: "Swap memory usage on {{ $labels.instance }} is above 80% for more than 2 minutes."

      - alert: NodeDown
        expr: up{job="node"} == 0
        for: 5m
        labels:
          severity: critical
          alertname: NodeDown
        annotations:
          summary: "Node {{ $labels.instance }} is down"
          description: "The node {{ $labels.instance }} has been unreachable for more than 5 minutes."

