global:
  scrape_interval: 30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'my-project'

rule_files:
  - "alertmanager/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.68.10:9100', '192.168.68.11:9100']
    relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance

  - job_name: 'ping-exporter'
    static_configs:
      - targets: ['192.168.68.11:9427']
    relabel_configs:
      - source_labels: [__name__]
        regex: "ping_loss_ratio"
        target_label: __name__
        replacement: "ping_loss_percent"

  - job_name: 'sonarr-exporter'
    static_configs:
      - targets: ['192.168.68.10:9707']

  - job_name: 'radarr-exporter'
    static_configs:
      - targets: ['192.168.68.10:9708']

  - job_name: 'bazarr-exporter'
    static_configs:
      - targets: ['192.168.68.10:9712']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.68.10:8081', '192.168.68.11:8081']
    relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect_example]
    static_configs:
     - targets:
        - 192.168.68.10:2049
        - 192.168.68.10:22
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://tv.dpinhas.duckdns.org
        - https://movies.dpinhas.duckdns.org
        - https://index.dpinhas.duckdns.org
        - https://proxy.dpinhas.duckdns.org
        - https://subtitles.dpinhas.duckdns.org
        - https://play.dpinhas.duckdns.org
        - https://prometheus.dpinhas.duckdns.org
        - https://grafana.dpinhas.duckdns.org
        - https://download.dpinhas.duckdns.org
        - https://adguard.dpinhas.duckdns.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp]

    static_configs:
      - targets: ['8.8.8.8', '8.8.4.4', '1.1.1.1', '1.0.0.1', '194.90.0.1']
        labels:
          group: 'external_network'
      - targets: ['192.168.68.1', '192.168.68.10']
        labels:
          group: 'internal_network'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'traefik'
#    scheme: https
    static_configs:
      - targets: ['proxy.dpinhas.duckdns.org']
    metrics_path: "/metrics"
