---
- name: Retrieve UUID from the attached filesystems
  ansible.builtin.shell:
    cmd: blkid | grep sda | awk -F '\"' '{print $2}'
  register: uuid

- name: Set disk_uuid variable
  ansible.builtin.set_fact:
    disk_uuid: "UUID={{ uuid.stdout }}"

- name: Mount SSD Storage into /mnt/data
  ansible.posix.mount:
    path: /mnt/data
    src: "{{ disk_uuid }}"
    fstype: ext4
    opts: "defaults,noatime"
    state: mounted

- name: Install nfs-server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: latest

- name: Ensure required entries are made to hosts file
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ item }}"
  loop:
    - "/mnt/data/       192.168.31.0/24(rw,sync,no_subtree_check)"

- name: Start nfs-server
  ansible.builtin.service:
    name: nfs-server
    state: restarted
    enabled: true

- name: Ensure the directory is ready for NFS usages
  ansible.builtin.command: exportfs -rav
