---
- name: Retrieve UUID from the attached filesystems
  shell: |
    blkid | grep sda | awk -F '\"' '{print $2}'
  register: uuid

- name: Set as variable
  set_fact:
    disk_uuid: "UUID={{ uuid.stdout }}"

- name: Mount SSD Storage into /mnt/data
  mount:
    path: /mnt/data
    src: "{{ disk_uuid }}"
    fstype: "ext4"
    opts: "defaults,noatime"
    state: "mounted"

- name: Install nfs-server
  apt: name=nfs-kernel-server state=latest

- name: Start nfs-server
  service:
    name: "nfs-server"
    enabled: yes
    state: started

- name: Ensure required entries are made to hosts file
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  loop:
    - '/mnt/data/       192.168.31.0/24(rw,sync,no_subtree_check)'

- name: Ensure the directory is ready for nfs usages
  shell: exportfs -rav

  



