global:
  scrape_interval: 30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'my-project'

rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.31.10:9100', '192.168.31.11:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.31.10:8081', '192.168.31.11:8081']

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect_example]
    static_configs:
     - targets:
        - 192.168.31.10:2049
        - 192.168.31.10:22
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115


  - job_name: 'blackbox_dns'
    scrape_timeout: 20s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://www.google.com
        - https://one.one.one.one
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp]

    static_configs:
      - targets: ['8.8.8.8', '8.8.4.4', '1.1.1.1', '1.0.0.1', '9.9.9.9' , '208.67.222.222']
        labels:
          group: 'external_network'
      - targets: ['192.168.31.1', '192.168.31.10', '10.100.102.1', '10.100.102.4']
        labels:
          group: 'internal_network'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

