apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: plex-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-tv
  namespace: media
spec:
  storageClassName: manual
  volumeName: plex-pv-tv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-movies
  namespace: media
spec:
  storageClassName: manual
  volumeName: plex-pv-movies
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 400Gi
