apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: radarr-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-movies
  namespace: media
spec:
  storageClassName: manual
  volumeName: radarr-pv-movies
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-downloads
  namespace: media
spec:
  storageClassName: manual
  volumeName: radarr-pv-downloads
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
