apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-config
  namespace: media
spec:
  storageClassName: manual
  volumeName: sonarr-pv-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-tv
  namespace: media
spec:
  storageClassName: manual
  volumeName: sonarr-pv-tv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-downloads
  namespace: media
spec:
  storageClassName: manual
  volumeName: sonarr-pv-downloads
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
